### ISSUE TITLE
audio.load(...) leaks memory

### ISSUE THREAD

**Issue by bobbens** [soumith/lua---audio#1]
I've been trying to debug exactly where it's leaking, but it seems like valgrind and the likes don't like luajit a lot. However, my tests show that indeed audio.load() does leak memory. Reproduce with:

```
require 'audio'
while true do
   data = audio.load( 'voice.mp3' )
   collectgarbage()
end
```

It will eventually get killed by the OOM-killer if you let it run long enough.

**Comment by soumith** [comment]
interesting. I'll take a look at this. thanks for the issue.

**Comment by soumith** [comment]
Sorry for the delay, fixed via commit: https://github.com/soumith/lua---audio/commit/db6ccf0969a6de6f7bacc2e2b7c930b18017c8e6

**Comment by bobbens** [comment]
Thanks for the fix!
