### ISSUE TITLE
torch.CudaTensor doesn't contain field 'libsox'.

### ISSUE THREAD

**Issue by NicholasYuan** [soumith/lua---audio#13]
When I finished calculating CudaTensor on GPU, I try to save audio (Type() = CudaTensor) with
`audio.save(('path'), music, 44100)`

Error happened 

```
/home/exp/torch/install/bin/luajit: /home/exp/torch/install/share/lua/5.1/audio/init.lua:74: attempt to index field 'libsox' (a nil value)
stack traceback:
    /home/exp/torch/install/share/lua/5.1/audio/init.lua:74: in function 'save'
    sample_music.lua:155: in main chunk
    [C]: in function 'dofile'
    .../exp/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00405ea0
```

So I must transform torch.CudaTensor to torch.DoubleTensor.

By the way, I don't know why I can't save `music` to mp3 correctly. When I save `music` to mp3, I get a very small file that can't play.

**Comment by soumith** [comment]
saving to mp3 depends on your version of libsox. Try mp3 or ogg, hopefully one of them will work.

and yes you have to typecast the tensor to DoubleTensor or FloatTensor before giving it to audio.save
