### ISSUE TITLE
formats: no handler for file extension `mp3'

### ISSUE THREAD

**Issue by moontails** [soumith/lua---audio#2]
I was following the steps in the example on readme when I encountered this error.

> require 'audio'
> require 'image'
> voice = audio.samplevoice()
> formats: no handler for file extension `mp3'
> [read_audio_file] Failure to read file
> Aborted (core dumped)

**Comment by soumith** [comment]
I think you'll have to install the additional non-free plugins for sox. which OS are you using?

**Comment by moontails** [comment]
I am using a ubuntu 14.04 LTS

**Comment by soumith** [comment]
sudo apt-get install libsox-fmt-all

it should have already been installed (if you used torch's install instructions) and has mp3 support. If not, install again.

**Comment by moontails** [comment]
yeah i did follow all the instructions to get torch installed! i think i have the latest version as well

libsox-fmt-all is already the newest version.

**Comment by moontails** [comment]
i am able to load my own wav file just fine. not sure if this helps

**Comment by soumith** [comment]
hmm, in the terminal if you type "sox", there's a lot of output, and you'll have a line like this:

```
AUDIO FILE FORMATS: 8svx aif aifc aiff aiffc al amb amr-nb amr-wb anb au avr awb caf cdda cdr cvs cvsd cvu dat dvms f32 f4 f64 f8 fap flac fssd gsm gsrt hcom htk ima ircam la lpc lpc10 lu mat mat4 mat5 maud mp2 mp3 nist ogg paf prc pvf raw s1 s16 s2 s24 s3 s32 s4 s8 sb sd2 sds sf sl sln smp snd sndfile sndr sndt sou sox sph sw txw u1 u16 u2 u24 u3 u32 u4 u8 ub ul uw vms voc vorbis vox w64 wav wavpcm wv wve xa xi
PLAYLIST FORMATS: m3u pls
AUDIO DEVICE DRIVERS: alsa ao oss ossdsp pulseaudio
```

Is there mp3 in there?

**Comment by moontails** [comment]
no i do not see mp3 listed there :/

**Comment by soumith** [comment]
hmm that's strange. my ubuntu has them....

**Comment by lolz0r** [comment]
I saw this problem today. It ends up using the audio library in a separate thread causes this problem; when using audio.load in the main thread it works as expected.

**Comment by felixsanz** [comment]
@soumith can you reopen this please? I'm having this issue with sox 14.4.2

**Comment by kavikon** [comment]
@felixsanz I still see this issue in 14.4.2 just compiled in ubuntu with latest issue is still there i dont see mp3 in the list as well

**Comment by kavikon** [comment]
please reopen this issue

**Comment by ankitshah009** [comment]
Any solution to this problem 
Able to see the issue with sox 14.4.1

**Comment by ankitshah009** [comment]
Please reopen the issue

**Comment by ashutosh1919** [comment]
Can anyone tell me solution for CentOS 7

**Comment by Otumian-empire** [comment]
> yeah i did follow all the instructions to get torch installed! i think i have the latest version as well
> 
> libsox-fmt-all is already the newest version.

this solution helped.. thanks
