### ISSUE TITLE
Apple .m4a?

### ISSUE THREAD

**Issue by watts4speed** [soumith/lua---audio#7]
I'm running on Ubuntu 14.04.  I was wondering is there a way to add support for the .m4a files that come from iTunes?

Here the sox output:
AUDIO FILE FORMATS: 8svx aif aifc aiff aiffc al amb amr-nb amr-wb anb au avr awb caf cdda cdr cvs cvsd cvu dat dvms f32 f4 f64 f8 fap flac fssd gsm gsrt hcom htk ima ircam la lpc lpc10 lu mat mat4 mat5 maud mp2 mp3 nist ogg paf prc pvf raw s1 s16 s2 s24 s3 s32 s4 s8 sb sd2 sds sf sl sln smp snd sndfile sndr sndt sou sox sph sw txw u1 u16 u2 u24 u3 u32 u4 u8 ub ul uw vms voc vorbis vox w64 wav wavpcm wv wve xa xi
PLAYLIST FORMATS: m3u pls
AUDIO DEVICE DRIVERS: alsa ao oss ossdsp pulseaudio

**Comment by soumith** [comment]
@watts4speed lua---audio supports whatever sox supports. Sox supports whatever decoders are likely on the machine. So the short answer is no. You can use ffmpeg to convert your .m4a files to something that is listed in the AUDIO FILE FORMATS for you.
