### ISSUE TITLE
Extreme range of audio data samples

### ISSUE THREAD

**Issue by thelinuxmaniac** [soumith/lua---audio#9]
Hi,
For a 16 bit PCM audio sampled at 11,025 Hz, I would expect the numeric range of audio samples to be (-32768,32768) (i.e. the range of 16 bit signed integer). This is true when I open an audio file using any other library (like using the tuneR in R package) as shown below: 

![audio_sample_hist_r](https://cloud.githubusercontent.com/assets/722415/12514677/ccfb9606-c124-11e5-835b-1f766d368fc0.png)

However, when I load the same audio file using lua--audio's audio.load() function, the number range is extremely large -- a DoubleTensor with range (-2147483648, 1719271424) as shown below:

![audio_sample_hist_lua](https://cloud.githubusercontent.com/assets/722415/12514728/05eb9010-c125-11e5-8ea2-eff1c64d47b4.png)

Can someone tell me why is this the case? Furthermore, how can I convert the DoubleTensor values to a signed 16 bit integer?

**Comment by soumith** [comment]
libsox which is used as the loading library uses 32-bit int for all its operations. The upscaling is probably due to that and harmless. You can scale down via a simple division.

**Comment by thelinuxmaniac** [comment]
Yes, I confirm that re-scaling the numbers to 16 bit integer gives the expected results. Thanks

```
require 'audio'
require 'gnuplot'

f = "11k16bitpcm.wav"
d, fs = audio.load(f)

d:div(2^31):mul(2^15)

gnuplot.pngfigure("audio_sample_hist.png")
gnuplot.hist(d[{{},1}], 13, -35000, 30000)
gnuplot.plotflush()
```

![audio_sample_hist](https://cloud.githubusercontent.com/assets/722415/12545415/5302ecc6-c342-11e5-86b0-b5723c9d596d.png)
